server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://101.35.193.165:3306/video?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: caiwenjing
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 81920MB
      max-request-size: 81920MB
filepathconfig:
  fileUrl: /upload/video
  imagePath: /images/
  videopath: /videos/
  enclosurepath: /enclosure/
files:
  ip: localhost